name: Create Artifact
on: push
env:
  ARTIFACT_NAME: "cool-artifact.txt"
jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v3
      - name: "upload artifact"
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
          retention-days: 2
