name: Complex workflow
on: push
jobs:
  ubuntu:
    name: See date on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - run: date
  windows:
    name: See date on Windows
    runs-on: windows-latest
    steps:
      - run: date
  macos:
    name: See date on MacOS
    runs-on: macos-latest
    steps:
      - run: date
  end:
    name: See environment on dependent job
    runs-on: ubuntu-latest
    needs: [ubuntu, windows, macos]
    steps:
      - run: date
